from __future__ import annotations

from typing import Protocol

from .modelos import CertificadoMedico, ConsultaAuditoria, Diagnostico


class CatalogoDiagnostico(Protocol):
    @property
    def simulada(self) -> bool: ...

    @property
    def dueno_dato(self) -> str: ...

    def obtener(self, codigo: str) -> Diagnostico | None: ...


class RepositorioSalud(Protocol):
    def guardar(self, certificado: CertificadoMedico) -> None: ...
    def obtener(self, certificado_id: str) -> CertificadoMedico | None: ...
    def listar(self) -> list[CertificadoMedico]: ...
    def auditar(self, consulta: ConsultaAuditoria) -> None: ...
