from __future__ import annotations

from typing import Protocol

from .modelos import AdjuntoSalud, CertificadoMedico, ConsultaAuditoria, Diagnostico


class CatalogoDiagnostico(Protocol):
    @property
    def simulada(self) -> bool: ...

    @property
    def dueno_dato(self) -> str: ...

    def obtener(self, codigo: str) -> Diagnostico | None: ...
    def listar(self) -> list[Diagnostico]: ...


class RepositorioSalud(Protocol):
    def guardar(self, certificado: CertificadoMedico) -> None: ...
    def obtener(self, certificado_id: str) -> CertificadoMedico | None: ...
    def listar(self) -> list[CertificadoMedico]: ...
    def auditar(self, consulta: ConsultaAuditoria) -> None: ...
    def listar_auditoria(self) -> list[ConsultaAuditoria]: ...


class RepositorioAdjuntosSalud(Protocol):
    def guardar(self, adjunto: AdjuntoSalud) -> None: ...
    def obtener(self, adjunto_id: str) -> AdjuntoSalud | None: ...


class FuenteLaboralArticulo208(Protocol):
    @property
    def simulada(self) -> bool: ...
    def obtener(self, legajo: str) -> tuple[int, int] | None: ...
