from __future__ import annotations

from typing import Protocol

from .modelos import Asistencia, Dictado, Tema


class RepositorioCapacitacion(Protocol):
    def guardar_tema(self, tema: Tema) -> None: ...

    def guardar_dictado(self, dictado: Dictado) -> None: ...

    def guardar_asistencia(self, asistencia: Asistencia) -> None: ...

    def obtener_tema(self, tema_id: str) -> Tema | None: ...

    def obtener_dictado(self, dictado_id: str) -> Dictado | None: ...

    def dictados_del_tema(self, tema_id: str) -> list[Dictado]: ...

    def asistencias_del_dictado(self, dictado_id: str) -> list[Asistencia]: ...

    def todas_las_asistencias(self) -> list[Asistencia]: ...


class ConfiguracionAsistencia(Protocol):
    @property
    def estado(self) -> str: ...

    @property
    def dueno_dato(self) -> str: ...

    @property
    def umbral_supervisor(self) -> float: ...

