"use client";

import { FormEvent, useEffect, useState } from "react";
import { api } from "@/lib/api";
import { ErrorVisible, Simulado, Tabla, Vacio } from "./compartidos";

type Dictado = { id: string; fecha: string; instructor: string; duracion_horas: number; convocatoria_tipo?: string; convocatoria_detalle?: string; convocados: string[] };
type Tema = Record<string, unknown> & { id: string; nombre: string; horas: number; periodicidad_meses?: number; dictados: Dictado[] };
type Asistencia = Record<string, unknown> & { participante: { legajo: string; nombre_completo: string }; presente: boolean; anulada: boolean; anulacion?: { motivo: string; anulada_por: string; anulada_en: string } };
type Reporte = { tema?: { asistentes: number; convocados: number | null; porcentaje: number | null; convocatoria: unknown[]; fecha_corte: string }; porcentaje_persona?: number | null; horas_persona?: number | null; fecha_corte: string; supervisores_baja_asistencia: Array<{ legajo: string; porcentaje: number }>; recapacitaciones: Array<Record<string, unknown>> };

export function CapacitacionesGestion() {
  const [temas, setTemas] = useState<Tema[]>([]); const [temaId, setTemaId] = useState("");
  const [dictadoId, setDictadoId] = useState(""); const [asistencias, setAsistencias] = useState<Asistencia[]>([]);
  const [reporte, setReporte] = useState<Reporte | null>(null); const [error, setError] = useState("");
  const [previa, setPrevia] = useState<Record<string, unknown> | null>(null);
  const [personaReporte, setPersonaReporte] = useState<Reporte | null>(null);
  const informar = (x: unknown) => setError(x instanceof Error ? x.message : "No se pudo completar la operación.");
  async function recargar() { try { const datos = await api<Tema[]>("capacitaciones/temas"); setTemas(datos); if (!temaId && datos[0]) setTemaId(datos[0].id); } catch (x) { informar(x); } }
  useEffect(() => { recargar(); }, []);
  useEffect(() => { if (temaId) api<Reporte>(`capacitaciones/reportes?tema_id=${temaId}`).then(setReporte).catch(informar); }, [temaId, asistencias]);
  useEffect(() => { if (dictadoId) api<Asistencia[]>(`capacitaciones/dictados/${dictadoId}/asistencias`).then(setAsistencias).catch(informar); }, [dictadoId]);
  async function crearTema(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); try { await api("capacitaciones/temas", { method: "POST", body: JSON.stringify({ nombre: f.get("nombre"), horas: Number(f.get("horas")), periodicidad_meses: f.get("periodicidad") ? Number(f.get("periodicidad")) : null }) }); e.currentTarget.reset(); await recargar(); } catch (x) { informar(x); } }
  async function crearDictado(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const tipo = String(f.get("convocatoria_tipo") || ""); try { await api("capacitaciones/dictados", { method: "POST", body: JSON.stringify({ tema_id: f.get("tema_id"), fecha: f.get("fecha"), instructor: f.get("instructor"), duracion_horas: Number(f.get("duracion")), convocatoria_tipo: tipo || null, convocatoria_detalle: f.get("detalle") || null, convocados: String(f.get("convocados") || "").split(",").map(x => x.trim()).filter(Boolean) }) }); e.currentTarget.reset(); await recargar(); } catch (x) { informar(x); } }
  async function tomar(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); try { await api(`capacitaciones/dictados/${dictadoId}/asistencias`, { method: "POST", body: JSON.stringify({ legajo: f.get("legajo"), nombre_completo: f.get("nombre"), presente: true, supervisor: f.get("supervisor") === "on", metodo_firma: f.get("firma") === "tablet" ? "TRAZO_TABLET" : null, evidencia_firma: f.get("firma") === "tablet" ? "trazo-confirmado" : null }) }); e.currentTarget.reset(); setAsistencias(await api(`capacitaciones/dictados/${dictadoId}/asistencias`)); } catch (x) { informar(x); } }
  async function anular(a: Asistencia) { const motivo = window.prompt("Motivo obligatorio de la anulación"); if (!motivo) return; try { await api(`capacitaciones/dictados/${dictadoId}/asistencias/${a.participante.legajo}/anular`, { method: "POST", body: JSON.stringify({ motivo }) }); setAsistencias(await api(`capacitaciones/dictados/${dictadoId}/asistencias`)); } catch (x) { informar(x); } }
  async function previsualizar(archivo?: File) { if (!archivo) return; const contenido_base64 = await new Promise<string>((ok, mal) => { const lector = new FileReader(); lector.onerror = mal; lector.onload = () => ok(String(lector.result).split(",")[1]); lector.readAsDataURL(archivo); }); try { setPrevia(await api("capacitaciones/historico/importaciones", { method: "POST", body: JSON.stringify({ contenido_base64 }) })); } catch (x) { informar(x); } }
  async function aplicarHistorico() { if (!previa?.id) return; try { await api(`capacitaciones/historico/importaciones/${previa.id}/aplicar`, { method: "POST" }); setPrevia(null); await recargar(); } catch (x) { informar(x); } }
  async function consultarPersona(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); try { setPersonaReporte(await api(`capacitaciones/reportes?legajo=${f.get("legajo")}&anio=${f.get("anio")}`)); } catch (x) { informar(x); } }
  const dictados = temas.flatMap(t => t.dictados.map(d => ({ ...d, tema: t.nombre })));
  return <>{error && <ErrorVisible mensaje={error} />}<div className="rejilla">
    <section className="tarjeta"><h2>Nuevo tema</h2><form className="form-grid" onSubmit={crearTema}><label>Nombre<input name="nombre" required /></label><label>Horas<input name="horas" type="number" min="0.5" step="0.5" required /></label><label>Periodicidad en meses — la define HyS<input name="periodicidad" type="number" min="1" /></label><button className="primario">Crear tema</button></form></section>
    <section className="tarjeta"><h2>Nuevo dictado</h2><form className="form-grid" onSubmit={crearDictado}><label>Tema<select name="tema_id" required>{temas.map(t => <option value={t.id} key={t.id}>{t.nombre}</option>)}</select></label><label>Fecha<input name="fecha" type="date" required /></label><label>Instructor<input name="instructor" required /></label><label>Duración<input name="duracion" type="number" min="0.5" step="0.5" required /></label><label>Convocatoria<select name="convocatoria_tipo"><option value="">Sin convocatoria</option><option value="SECTOR">Sector</option><option value="PUESTO">Puesto</option><option value="LISTA">Lista</option></select></label><label>Detalle<input name="detalle" /></label><label>Legajos convocados, separados por coma<input name="convocados" /></label><button className="primario">Crear dictado</button></form></section>
    <section className="tarjeta"><div className="titulo-fila"><h2>Temas y dictados</h2><Simulado nivel="tabla" /></div>{temas.length ? <Tabla etiqueta="Temas de capacitación" filas={temas} columnas={[{ clave: "nombre", titulo: "Tema" }, { clave: "horas", titulo: "Horas" }, { clave: "periodicidad_meses", titulo: "Recapacitación", valor: f => f.periodicidad_meses ? `Cada ${f.periodicidad_meses} meses` : "Sin plazo definido" }, { clave: "dictados", titulo: "Dictados", valor: f => f.dictados.length }]} /> : <Vacio>No hay temas.</Vacio>}<label>Dictado para asistencia<select value={dictadoId} onChange={e => setDictadoId(e.target.value)}><option value="">Seleccionar</option>{dictados.map(d => <option key={d.id} value={d.id}>{d.tema} · {d.fecha}</option>)}</select></label></section>
    {dictadoId && <section className="tarjeta"><h2>Toma de asistencia</h2><form className="form-grid" onSubmit={tomar}><label>Legajo<input name="legajo" required /></label><label>Nombre<input name="nombre" required /></label><label>Firma<select name="firma"><option value="papel">Pendiente en planilla impresa</option><option value="tablet">Firma en tablet (simulada)</option></select></label><label><input type="checkbox" name="supervisor" /> Es supervisor</label><button className="primario">Registrar asistencia</button><a className="boton" target="_blank" href={`${process.env.NEXT_PUBLIC_API_URL ?? "/backend"}/capacitaciones/dictados/${dictadoId}/planilla`}>Imprimir planilla</a></form>{asistencias.length ? <Tabla etiqueta="Asistencias" filas={asistencias} columnas={[{ clave: "participante", titulo: "Persona", valor: f => `${f.participante.legajo} · ${f.participante.nombre_completo}` }, { clave: "presente", titulo: "Estado", valor: f => f.anulada ? `Anulada: ${f.anulacion?.motivo}` : f.presente ? "Presente" : "Ausente" }, { clave: "accion", titulo: "Auditoría", valor: f => f.anulada ? `${f.anulacion?.anulada_por} · ${f.anulacion?.anulada_en}` : <button onClick={() => anular(f as Asistencia)}>Anular con motivo</button> }]} /> : <Vacio>Sin asistencias.</Vacio>}</section>}
    <section className="tarjeta"><h2>Reporte por tema</h2><label>Tema<select value={temaId} onChange={e => setTemaId(e.target.value)}>{temas.map(t => <option key={t.id} value={t.id}>{t.nombre}</option>)}</select></label>{reporte?.tema && <div className="metricas"><article><span>Asistentes únicos</span><strong>{reporte.tema.asistentes}</strong><small>Una persona cuenta una vez aunque vaya a dos tandas</small></article><article><span>Asistencia</span><strong>{reporte.tema.porcentaje === null ? "Cantidad, sin %" : `${reporte.tema.porcentaje}%`}</strong><small>{reporte.tema.convocados === null ? "Sin convocatoria declarada" : `${reporte.tema.convocados} convocados`}</small></article><article><span>Fecha de corte</span><strong>{reporte.tema.fecha_corte}</strong><small>Convocatoria visible en el detalle</small></article></div>}</section>
    <section className="tarjeta"><h2>Reporte por persona y año</h2><form className="form-linea" onSubmit={consultarPersona}><label>Legajo del reporte<input name="legajo" required /></label><label>Año<input name="anio" type="number" defaultValue={new Date().getFullYear()} required /></label><button className="primario">Consultar</button></form>{personaReporte && <p><strong>{personaReporte.horas_persona ?? 0} horas</strong> · {personaReporte.porcentaje_persona === null ? "Sin convocatoria para calcular porcentaje" : `${personaReporte.porcentaje_persona}% de temas convocados`} · corte {personaReporte.fecha_corte}</p>}</section>
    <section className="tarjeta"><h2>Supervisores con asistencia baja</h2>{reporte?.supervisores_baja_asistencia.length ? <pre>{JSON.stringify(reporte.supervisores_baja_asistencia, null, 2)}</pre> : <Vacio>Sin alertas calculables.</Vacio>}</section>
    <section className="tarjeta"><h2>Recapacitaciones</h2><p className="ayuda">Sólo se generan cuando Higiene y Seguridad definió la periodicidad del tema.</p>{reporte?.recapacitaciones.length ? <pre>{JSON.stringify(reporte.recapacitaciones, null, 2)}</pre> : <Vacio>Sin vencimientos configurados.</Vacio>}</section>
    <section className="tarjeta"><h2>Carga del histórico de RRHH</h2><p className="ayuda">Previsualiza altas, coincidencias y desapariciones. Las desapariciones nunca se borran del histórico.</p><label className="carga">Excel histórico<input aria-label="Excel histórico" type="file" accept=".xlsx" onChange={e => previsualizar(e.target.files?.[0])} /></label>{previa && <div className="previsualizacion"><pre>{JSON.stringify(previa, null, 2)}</pre><button className="primario" onClick={aplicarHistorico}>Aplicar histórico conservando anteriores</button></div>}</section>
  </div></>;
}
