"use client";

import { FormEvent, useEffect, useState } from "react";
import { api } from "@/lib/api";
import { ErrorVisible, Simulado, Tabla, Vacio } from "./compartidos";

type Diagnostico = { codigo: string; descripcion: string; padre_codigo?: string };
type Certificado = Record<string, unknown> & { id: string; legajo: string; diagnostico_codigo: string; desde: string; hasta: string; dias: number; profesional: string };
type Auditoria = Record<string, unknown> & { id: string; actor: string; momento: string; legajo?: string; accion: string };
type Reporte = { por_diagnostico: Array<Record<string, unknown>>; por_estacion: Array<Record<string, unknown>>; grupos_suprimidos: number; minimo_agregado: number };
type Articulo = { aplica: boolean; estado: string; leyenda: string; imprimible: boolean; exportable: boolean };

async function base64(archivo: File) { return new Promise<string>((ok, mal) => { const lector = new FileReader(); lector.onerror = mal; lector.onload = () => ok(String(lector.result).split(",")[1]); lector.readAsDataURL(archivo); }); }

export function SaludGestion() {
  const [catalogo, setCatalogo] = useState<Diagnostico[]>([]); const [certificados, setCertificados] = useState<Certificado[]>([]);
  const [reporte, setReporte] = useState<Reporte | null>(null); const [auditoria, setAuditoria] = useState<Auditoria[]>([]);
  const [articulo, setArticulo] = useState<Articulo | null>(null); const [error, setError] = useState(""); const [mensaje, setMensaje] = useState("");
  const informar = (x: unknown) => setError(x instanceof Error ? x.message : "No se pudo completar la operación.");
  async function iniciar() { try { const c = await api<{ items: Diagnostico[] }>("salud/catalogo"); setCatalogo(c.items); setCertificados(await api("salud/certificados")); } catch (x) { informar(x); } }
  useEffect(() => { iniciar(); }, []);
  async function cargar(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setError(""); const form = e.currentTarget; const f = new FormData(form); const archivo = f.get("adjunto") as File; try { const creado = await api<Certificado>("salud/certificados", { method: "POST", body: JSON.stringify({ legajo: f.get("legajo"), diagnostico_codigo: f.get("diagnostico_codigo"), desde: f.get("desde"), hasta: f.get("hasta"), dias: Number(f.get("dias")), profesional: f.get("profesional"), adjunto_nombre: archivo.name, adjunto_base64: await base64(archivo) }) }); setMensaje(`Certificado ${creado.id} registrado y auditado.`); form.reset(); setCertificados(await api("salud/certificados")); } catch (x) { informar(x); } }
  async function filtrar(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const q = new URLSearchParams(); for (const k of ["legajo", "desde", "hasta"]) { const v = String(f.get(k) || ""); if (v) q.set(k, v); } try { setCertificados(await api(`salud/certificados?${q}`)); } catch (x) { informar(x); } }
  async function cargarReporte() { try { setReporte(await api("salud/reportes")); } catch (x) { informar(x); } }
  async function cargarAuditoria(e?: FormEvent<HTMLFormElement>) { e?.preventDefault(); const q = new URLSearchParams(); if (e) { const f = new FormData(e.currentTarget); for (const k of ["usuario", "legajo", "desde", "hasta"]) { const v = String(f.get(k) || ""); if (v) q.set(k, v); } } try { setAuditoria(await api(`salud/bitacora?${q}`)); } catch (x) { informar(x); } }
  async function consultar208(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const legajo = new FormData(e.currentTarget).get("legajo"); try { setArticulo(await api(`salud/articulo-208?legajo=${legajo}`)); } catch (x) { informar(x); } }
  return <>{error && <ErrorVisible mensaje={error} />}{mensaje && <div className="aviso-exito" role="status">{mensaje}</div>}<div className="rejilla">
    <section className="tarjeta"><div className="titulo-fila"><h2>Nuevo certificado médico</h2><Simulado nivel="tabla" /></div><p className="ayuda">Catálogo jerárquico de muestra. Dueño del dato: Servicio Médico.</p><form className="form-grid" onSubmit={cargar}><label>Legajo<input name="legajo" required /></label><label>Diagnóstico del catálogo<select name="diagnostico_codigo" required><option value="">Seleccionar</option>{catalogo.filter(x => x.padre_codigo).map(x => <option key={x.codigo} value={x.codigo}>{catalogo.find(p => p.codigo === x.padre_codigo)?.descripcion} › {x.descripcion}</option>)}</select></label><label>Desde<input name="desde" type="date" required /></label><label>Hasta<input name="hasta" type="date" required /></label><label>Días corridos<input name="dias" type="number" min="1" required /></label><label>Profesional<input name="profesional" required /></label><label>Escaneo original<input name="adjunto" type="file" required /></label><button className="primario">Registrar certificado</button></form></section>
    <section className="tarjeta"><h2>Certificados</h2><form className="form-grid" onSubmit={filtrar}><label>Legajo<input name="legajo" /></label><label>Desde<input name="desde" type="date" /></label><label>Hasta<input name="hasta" type="date" /></label><button>Aplicar filtros</button></form>{certificados.length ? <Tabla etiqueta="Certificados médicos" filas={certificados} columnas={[{ clave: "legajo", titulo: "Legajo" }, { clave: "diagnostico_codigo", titulo: "Diagnóstico" }, { clave: "desde", titulo: "Desde" }, { clave: "hasta", titulo: "Hasta" }, { clave: "dias", titulo: "Días" }, { clave: "profesional", titulo: "Profesional" }]} /> : <Vacio>Sin certificados para los filtros elegidos.</Vacio>}</section>
    <section className="tarjeta"><h2>Aviso preliminar · artículo 208</h2><form className="form-linea" onSubmit={consultar208}><label>Legajo<input name="legajo" defaultValue="1042" required /></label><button>Evaluar</button></form>{articulo && <div className="preliminar"><strong>{articulo.estado} · {articulo.aplica ? "podría aplicar" : "no aplicaría"}</strong><p>{articulo.leyenda}</p><p>No se puede imprimir ni exportar mientras use datos simulados.</p></div>}</section>
    <section className="tarjeta"><div className="titulo-fila"><h2>Reportes agregados</h2><button onClick={cargarReporte}>Actualizar reporte</button></div><p className="ayuda">Nunca nominados. Los grupos de una sola persona se suprimen.</p>{reporte ? <><p>Mínimo de agregado: {reporte.minimo_agregado} · grupos suprimidos: {reporte.grupos_suprimidos}</p><Tabla etiqueta="Casos por diagnóstico" filas={reporte.por_diagnostico} columnas={[{ clave: "descripcion", titulo: "Diagnóstico" }, { clave: "personas", titulo: "Personas" }]} /><br /><Tabla etiqueta="Casos por estación" filas={reporte.por_estacion} columnas={[{ clave: "estacion", titulo: "Estación" }, { clave: "personas", titulo: "Personas" }]} /></> : <Vacio>Actualizá para consultar los agregados.</Vacio>}</section>
    <section className="tarjeta"><div className="titulo-fila"><h2>Bitácora inmutable</h2><span className="estado">Actor · fecha · legajo · acción</span></div><p className="ayuda">La bitácora nunca registra el diagnóstico. Consultarla también deja una entrada.</p><form className="form-grid" onSubmit={cargarAuditoria}><label>Usuario<input name="usuario" /></label><label>Legajo<input name="legajo" /></label><label>Desde<input name="desde" type="date" /></label><label>Hasta<input name="hasta" type="date" /></label><button>Consultar bitácora</button></form>{auditoria.length ? <Tabla etiqueta="Bitácora de accesos médicos" filas={auditoria} columnas={[{ clave: "actor", titulo: "Actor" }, { clave: "momento", titulo: "Momento" }, { clave: "legajo", titulo: "Legajo" }, { clave: "accion", titulo: "Acción" }]} /> : <Vacio>Consultá la bitácora para ver sus entradas.</Vacio>}</section>
  </div></>;
}
