"use client";

import { FormEvent, useEffect, useState } from "react";
import { api } from "@/lib/api";
import { ErrorVisible, Simulado, Tabla, Vacio } from "./compartidos";

type Busqueda = Record<string, unknown> & { id: string; nombre: string; perfil: string; definido_por: string; definido_en: string };
type Campo = { nombre: string; valor: string; fragmento: string; verificado: boolean };
type Cv = Record<string, unknown> & { id: string; nombre: string; requiere_revision: boolean; campos?: Campo[]; resultado?: { puntaje: number; razones: string[] } };
type Ficha = { id: string; nombre: string; campos: Campo[]; pendientes: string[]; confirmaciones: Array<{ campo: string; valor: string; confirmado_por: string; confirmado_en: string }>; resultado?: { puntaje: number; razones: string[] } };

export function SeleccionGestion() {
  const [busquedas, setBusquedas] = useState<Busqueda[]>([]); const [cvs, setCvs] = useState<Cv[]>([]); const [revision, setRevision] = useState<Cv[]>([]);
  const [busqueda, setBusqueda] = useState(""); const [ficha, setFicha] = useState<Ficha | null>(null); const [original, setOriginal] = useState(""); const [error, setError] = useState("");
  const informar = (e: unknown) => setError(e instanceof Error ? e.message : "No se pudo completar la operación.");
  async function recargar(id = busqueda) { try { const [b, c, r] = await Promise.all([api<Busqueda[]>("seleccion/busquedas"), api<Cv[]>(`seleccion/cvs${id ? `?busqueda_id=${id}` : ""}`), api<Cv[]>("seleccion/revision")]); setBusquedas(b); setCvs(c); setRevision(r); } catch (e) { informar(e); } }
  useEffect(() => { recargar(); }, []);
  async function crear(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const formulario = e.currentTarget; const f = Object.fromEntries(new FormData(formulario)); try { const creada = await api<Busqueda>("seleccion/busquedas", { method: "POST", body: JSON.stringify({ ...f, edad_minima: f.edad_minima ? Number(f.edad_minima) : null, edad_maxima: f.edad_maxima ? Number(f.edad_maxima) : null, secundaria_completa: f.secundaria_completa === "on" }) }); setBusqueda(creada.id); formulario.reset(); recargar(creada.id); } catch (x) { informar(x); } }
  async function cargar(archivos?: FileList | null) { if (!archivos?.length) return; const lote = await Promise.all(Array.from(archivos).map(async archivo => ({ nombre: archivo.name, contenido_base64: await new Promise<string>((ok, mal) => { const l = new FileReader(); l.onerror = mal; l.onload = () => ok(String(l.result).split(",")[1]); l.readAsDataURL(archivo); }) }))); try { await api("seleccion/cvs/lote", { method: "POST", body: JSON.stringify({ archivos: lote }) }); recargar(); } catch (x) { informar(x); } }
  async function abrir(cv: Cv) { try { setFicha(await api<Ficha>(`seleccion/cvs/${cv.id}${busqueda ? `?busqueda_id=${busqueda}` : ""}`)); const o = await api<{ contenido_base64: string }>(`seleccion/cvs/${cv.id}/original`); setOriginal(`data:application/pdf;base64,${o.contenido_base64}`); } catch (x) { informar(x); } }
  async function confirmar(campo: Campo) { if (!ficha) return; try { await api(`seleccion/cvs/${ficha.id}/campos/${campo.nombre}/confirmacion`, { method: "PUT", body: JSON.stringify({ valor: campo.valor }) }); await abrir({ id: ficha.id } as Cv); } catch (x) { informar(x); } }
  return <>{error && <ErrorVisible mensaje={error} />}<div className="rejilla"><section className="tarjeta"><h2>Abrir búsqueda</h2><form className="form-grid" onSubmit={crear}><label>Nombre<input name="nombre" required /></label><label>Perfil<select name="perfil"><option>BODEGA</option><option>MANTENIMIENTO</option><option>ADMINISTRACION</option></select></label><label>Edad mínima<input name="edad_minima" type="number" min="0" /></label><label>Edad máxima<input name="edad_maxima" type="number" min="0" /></label><label><span>Secundaria completa</span><input name="secundaria_completa" type="checkbox" /></label><button className="primario">Crear búsqueda</button></form></section>
    <section className="tarjeta"><div className="titulo-fila"><h2>Búsquedas abiertas</h2><Simulado nivel="tabla" /></div><select aria-label="Búsqueda para ranking" value={busqueda} onChange={e => { setBusqueda(e.target.value); recargar(e.target.value); }}><option value="">Sin ranking</option>{busquedas.map(b => <option key={b.id} value={b.id}>{b.nombre}</option>)}</select>{busquedas.length ? <Tabla etiqueta="Búsquedas" filas={busquedas} columnas={[{ clave: "nombre", titulo: "Búsqueda" }, { clave: "perfil", titulo: "Perfil" }, { clave: "definido_por", titulo: "Criterio por" }, { clave: "definido_en", titulo: "Fecha", valor: f => new Date(f.definido_en).toLocaleString("es-AR") }]} /> : <Vacio>No hay búsquedas abiertas.</Vacio>}</section>
    <section className="tarjeta"><div className="titulo-fila"><h2>Bandeja y ranking preliminar</h2><label className="carga">Carga manual<input type="file" multiple accept="application/pdf" onChange={e => cargar(e.target.files)} /></label></div><p className="preliminar">El ranking explica coincidencias sobre datos extraídos, pero ningún campo cuenta como confirmado hasta la acción manual registrada.</p>{cvs.length ? <Tabla etiqueta="CV recibidos" filas={cvs} columnas={[{ clave: "nombre", titulo: "Original" }, { clave: "requiere_revision", titulo: "Estado", valor: f => <span className={f.requiere_revision ? "estado estado-alerta" : "estado"}>{f.requiere_revision ? "Revisión" : "Procesado"}</span> }, { clave: "resultado", titulo: "Puntaje", valor: f => f.resultado?.puntaje ?? "—" }, { clave: "motivo", titulo: "Inclusión / exclusión", valor: f => f.resultado?.razones?.join(" · ") ?? "Sin evaluación" }, { clave: "abrir", titulo: "Ficha", valor: f => <button onClick={() => abrir(f as Cv)}>Abrir</button> }]} /> : <Vacio>Cargá uno o varios PDF para comenzar.</Vacio>}</section>
    <section className="tarjeta"><h2>Bandeja de revisión</h2>{revision.length ? <Tabla etiqueta="Ilegibles" filas={revision} columnas={[{ clave: "nombre", titulo: "Original" }, { clave: "estado", titulo: "Estado", valor: () => <span className="estado estado-alerta">Apartado para revisión</span> }, { clave: "abrir", titulo: "Acción", valor: f => <button onClick={() => abrir(f as Cv)}>Revisar</button> }]} /> : <Vacio>No hay CV ilegibles.</Vacio>}</section>
    {ficha && <section className="tarjeta"><div className="titulo-fila"><h2>Ficha: {ficha.nombre}</h2><Simulado nivel="campo" /></div><div className="ficha-doble"><div>{ficha.campos.map(c => <article className="campo-extraido" key={c.nombre}><strong>{c.nombre}: {c.valor}</strong><p>“{c.fragmento}”</p><span className="estado estado-alerta">No verificado</span>{ficha.confirmaciones.some(x => x.campo === c.nombre) ? <span className="estado">Confirmado manualmente</span> : <button onClick={() => confirmar(c)}>Confirmar este valor</button>}</article>)}</div>{original && <iframe className="visor visor-original" title="CV original" src={original} />}</div></section>}
  </div></>;
}
