"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { api } from "@/lib/api";
import { ErrorVisible, Simulado, Tabla, Vacio } from "./compartidos";

type Plan = Record<string, unknown> & { id: string; legajo: string; sector: string; fecha: string; desde: string; hasta: string; autor: string; conocido_en: string; cambio_tardio: boolean };
type Dia = Record<string, unknown> & { legajo: string; sector: string; fecha: string; desde_plan: string; hasta_plan: string; primera_marca?: string; ultima_marca?: string; minutos_desvio: number; tipo_desvio?: string; estado_dia: string; propuesta_id?: string };
type Propuesta = Record<string, unknown> & { id: string; legajo: string; sector: string; fecha: string; motivo_propuesto: string; minutos_desvio: number; estado: string; antiguedad_dias: number; aprobada_por?: string; resuelta_en?: string };
type Salida = Record<string, unknown> & { id: string; creada_en: string; estado: string; formato: string; archivo: string; cantidad_dias: number; personas: string[]; simulada: boolean };
type Cambio = Record<string, unknown> & { id: string; legajo: string; sector: string; fecha_afectada: string; desde_anterior: string; hasta_anterior: string; desde_nuevo: string; hasta_nuevo: string; autor: string; conocido_en: string; tardio: boolean };
type Reporte = { desde: string; hasta: string; por_sector: Array<Record<string, unknown> & { sector: string; dias_regularizados_tarde: number }> };

function fechaSumada(fecha: string, dias: number) { const d = new Date(`${fecha}T12:00:00`); d.setDate(d.getDate() + dias); return d.toISOString().slice(0, 10); }
function estadoLegible(valor: string) { return valor.replaceAll("_", " ").toLocaleLowerCase("es-AR"); }

export function TurnosGestion() {
  const [perfil, setPerfil] = useState(""); const [planes, setPlanes] = useState<Plan[]>([]); const [historial, setHistorial] = useState<Cambio[]>([]);
  const [dias, setDias] = useState<Dia[]>([]); const [propuestas, setPropuestas] = useState<Propuesta[]>([]); const [seleccion, setSeleccion] = useState<string[]>([]);
  const [bandeja, setBandeja] = useState<Salida[]>([]); const [reporte, setReporte] = useState<Reporte | null>(null); const [error, setError] = useState(""); const [mensaje, setMensaje] = useState("");
  const informar = (x: unknown) => setError(x instanceof Error ? x.message : "No se pudo completar la operación.");
  const pendientes = useMemo(() => propuestas.filter(x => x.estado === "PROPUESTA"), [propuestas]);
  async function recargar() { try { setPlanes(await api("turnos/cronogramas?sector=Bodega")); setHistorial(await api("turnos/cronogramas/historial?sector=Bodega")); setPropuestas(await api("turnos/propuestas")); } catch (x) { informar(x); } }
  useEffect(() => { const guardada = sessionStorage.getItem("gestion-sesion"); if (guardada) setPerfil(JSON.parse(guardada).perfil); recargar(); }, []);
  async function cargarSemana(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = e.currentTarget; const f = new FormData(form); const inicio = String(f.get("semana")); const asignaciones = Array.from({ length: 5 }, (_, i) => ({ legajo: f.get("legajo"), fecha: fechaSumada(inicio, i), desde: f.get("desde"), hasta: f.get("hasta") })); try { await api("turnos/cronogramas/semana", { method: "POST", body: JSON.stringify({ sector: "Bodega", asignaciones }) }); setMensaje("Semana registrada con autor y fecha de conocimiento en cada día."); await recargar(); } catch (x) { informar(x); } }
  async function cambioTardio(plan: Plan) { const desde = window.prompt("Nuevo horario desde (HH:MM)", plan.desde.slice(0, 5)); if (!desde) return; const hasta = window.prompt("Nuevo horario hasta (HH:MM)", plan.hasta.slice(0, 5)); if (!hasta) return; try { await api(`turnos/cronogramas/${plan.id}/cambio-tardio`, { method: "POST", body: JSON.stringify({ desde, hasta }) }); setMensaje("Cambio tardío registrado sin reescribir el cronograma original."); await recargar(); } catch (x) { informar(x); } }
  async function conciliar(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const q = new URLSearchParams({ desde: String(f.get("desde")), hasta: String(f.get("hasta")) }); for (const k of ["sector", "legajo"]) { const v = String(f.get(k) || ""); if (v) q.set(k, v); } try { setDias(await api(`turnos/conciliacion?${q}`)); setPropuestas(await api("turnos/propuestas")); } catch (x) { informar(x); } }
  async function resolver(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const accion = String(f.get("accion")); const personas = new Set(pendientes.filter(x => seleccion.includes(x.id)).map(x => x.legajo)).size; if (!window.confirm(`${accion}: ${seleccion.length} días de ${personas} personas. ¿Confirmar?`)) return; try { await api("turnos/propuestas/resolver-lote", { method: "POST", body: JSON.stringify({ ids: seleccion, accion, motivo_cambio: f.get("motivo") || null }) }); setSeleccion([]); setMensaje(`${seleccion.length} propuestas resueltas en lote.`); await recargar(); setBandeja(await api("turnos/bandeja")); } catch (x) { informar(x); } }
  async function salidasYReporte() { try { setBandeja(await api("turnos/bandeja")); setReporte(await api("turnos/reportes/regularizaciones-tardias?desde=2026-01-01&hasta=2026-12-31")); } catch (x) { informar(x); } }
  return <>{error && <ErrorVisible mensaje={error} />}{mensaje && <div className="aviso-exito" role="status">{mensaje}</div>}<div className="rejilla">
    {perfil === "SUPERVISOR" && <><section className="tarjeta"><div className="titulo-fila"><h2>Cronograma semanal · Bodega</h2><Simulado nivel="tabla" /></div><p className="ayuda">Tu perfil sólo puede operar Bodega. Cada fila conserva autor y fecha de conocimiento.</p><form className="form-grid" onSubmit={cargarSemana}><label>Semana desde el lunes<input name="semana" type="date" defaultValue="2026-09-14" required /></label><label>Legajo<input name="legajo" defaultValue="1042" required /></label><label>Turno desde<input name="desde" type="time" defaultValue="08:00" required /></label><label>Turno hasta<input name="hasta" type="time" defaultValue="16:00" required /></label><button className="primario">Registrar semana</button></form></section>
      <section className="tarjeta"><h2>Quién trabaja en cada turno</h2>{planes.length ? <Tabla etiqueta="Cronograma semanal" filas={planes} columnas={[{ clave: "fecha", titulo: "Día" }, { clave: "legajo", titulo: "Legajo" }, { clave: "sector", titulo: "Sector" }, { clave: "desde", titulo: "Desde" }, { clave: "hasta", titulo: "Hasta" }, { clave: "autor", titulo: "Autor" }, { clave: "conocido_en", titulo: "Conocido" }, { clave: "accion", titulo: "Día cerrado", valor: p => p.fecha < new Date().toISOString().slice(0, 10) ? <button onClick={() => cambioTardio(p)}>Registrar cambio tardío</button> : "Edición disponible" }]} /> : <Vacio>Sin cronogramas para tu sector.</Vacio>}</section>
      <section className="tarjeta"><h2>Historial de cambios</h2>{historial.length ? <Tabla etiqueta="Historial del cronograma" filas={historial} columnas={[{ clave: "fecha_afectada", titulo: "Día afectado" }, { clave: "legajo", titulo: "Legajo" }, { clave: "desde_anterior", titulo: "Antes" }, { clave: "desde_nuevo", titulo: "Después" }, { clave: "autor", titulo: "Autor" }, { clave: "conocido_en", titulo: "Cuándo se supo" }, { clave: "tardio", titulo: "Estado", valor: c => c.tardio ? "Regularizado tarde" : "Planificado" }]} /> : <Vacio>Sin cambios registrados.</Vacio>}</section></>}
    {perfil === "RRHH" && <><section className="tarjeta"><h2>Conciliación día por día</h2><form className="form-grid" onSubmit={conciliar}><label>Sector<input name="sector" defaultValue="Bodega" /></label><label>Persona por legajo<input name="legajo" /></label><label>Desde<input name="desde" type="date" defaultValue="2026-09-01" required /></label><label>Hasta<input name="hasta" type="date" defaultValue="2026-09-30" required /></label><button className="primario">Comparar plan y fichadas</button></form>{dias.length ? <Tabla etiqueta="Conciliación diaria" filas={dias} columnas={[{ clave: "fecha", titulo: "Día" }, { clave: "legajo", titulo: "Persona" }, { clave: "sector", titulo: "Sector" }, { clave: "desde_plan", titulo: "Plan" }, { clave: "primera_marca", titulo: "Fichadas", valor: d => d.primera_marca ? `${d.primera_marca} → ${d.ultima_marca}` : "Sin marcas" }, { clave: "tipo_desvio", titulo: "Desvío" }, { clave: "estado_dia", titulo: "Semáforo", valor: d => <span className={`estado estado-${d.estado_dia.toLowerCase()}`}>{estadoLegible(d.estado_dia)}</span> }, { clave: "propuesta_id", titulo: "Propuesta", valor: d => d.propuesta_id ? "Ver debajo" : "No requiere" }]} /> : <Vacio>Aplicá los filtros para conciliar.</Vacio>}</section>
      <section className="tarjeta"><div className="titulo-fila"><h2>Propuestas pendientes</h2><span className="estado estado-alerta">{pendientes.length} pendientes</span></div><p className="ayuda">Nada se autoimputa. La antigüedad sigue aumentando hasta que RRHH resuelva.</p>{pendientes.length ? <><div className="tabla-contenedor"><div className="tabla-scroll"><table><thead><tr><th>Seleccionar</th><th>Día</th><th>Persona</th><th>Sector</th><th>Motivo sugerido</th><th>Desvío</th><th>Antigüedad</th></tr></thead><tbody>{pendientes.map(p => <tr key={p.id}><td><input aria-label={`Seleccionar ${p.legajo} ${p.fecha}`} type="checkbox" checked={seleccion.includes(p.id)} onChange={e => setSeleccion(e.target.checked ? [...seleccion, p.id] : seleccion.filter(x => x !== p.id))} /></td><td>{p.fecha}</td><td>{p.legajo}</td><td>{p.sector}</td><td>{p.motivo_propuesto}</td><td>{p.minutos_desvio} min</td><td><strong>{p.antiguedad_dias} días</strong></td></tr>)}</tbody></table></div></div><form className="form-grid lote" onSubmit={resolver}><label>Acción en lote<select name="accion"><option value="APROBAR">Aprobar propuestas</option><option value="RECHAZAR">Rechazar</option><option value="CAMBIAR">Cambiar imputación</option></select></label><label>Motivo final si se cambia<input name="motivo" /></label><button className="primario" disabled={!seleccion.length}>Resolver {seleccion.length} seleccionadas</button></form></> : <Vacio>No hay desvíos pendientes.</Vacio>}</section>
      <section className="tarjeta"><div className="titulo-fila"><h2>Bandeja de salida y regularizaciones tardías</h2><button onClick={salidasYReporte}>Actualizar</button></div><p className="preliminar"><strong>Bandeja local simulada.</strong> Muestra qué se exportaría; no escribe en el sistema externo.</p>{bandeja.length ? <Tabla etiqueta="Bandeja de salida" filas={bandeja} columnas={[{ clave: "creada_en", titulo: "Generada" }, { clave: "estado", titulo: "Estado" }, { clave: "formato", titulo: "Formato" }, { clave: "cantidad_dias", titulo: "Días" }, { clave: "personas", titulo: "Personas", valor: s => s.personas.join(", ") }, { clave: "simulada", titulo: "Validez", valor: () => "SIMULADA · SIN VALIDEZ" }]} /> : <Vacio>Sin archivos generados.</Vacio>}<h3>Regularizaciones tardías por sector</h3>{reporte?.por_sector.length ? <Tabla etiqueta="Reporte de regularizaciones tardías" filas={reporte.por_sector} columnas={[{ clave: "sector", titulo: "Sector" }, { clave: "dias_regularizados_tarde", titulo: "Días regularizados tarde" }]} /> : <Vacio>Sin regularizaciones tardías en el período.</Vacio>}</section></>}
  </div></>;
}
